### ISSUE TITLE
本地开发环境部署调试文档

### ISSUE THREAD

**Issue by pengliren** [xl-xueling/xl-lighthouse#1]
能整一个本地开发环境部署调试文档吗，特别是ICE这块不怎么了解，想深入学习了解一下，看看能不能用到生产环境。

**Comment by pengliren** [comment]
还有一个就是建议建一个群，大家可以讨论交流。

**Comment by xl-xueling** [comment]
本地可以跑web服务和spark任务，其他像hadoop/hbase/zk/kafka/ice只能部署到测试环境（我自己开发用的是三台云服务器），关于这部分我会写个文档。
ICE是基于开源Zeroc-ICE框架实现的，本机部署ICE的话，可能比较麻烦，你得参考下这个：https://zeroc.com/downloads/ice/3.6。我自己也没有在mac上部署过ice。 如果要深入了解只能看官方文档了（https://doc.zeroc.com/ice/3.7/ice-overview ）。













在 2023-07-27 09:39:29，"pengliren" ***@***.***> 写道：

能整一个本地开发环境部署调试文档吗，特别是ICE这块不怎么了解，想深入学习了解一下，看看能不能用到生产环境。

**Comment by pengliren** [comment]
好的，整个测试环境文档也行

**Comment by xl-xueling** [comment]
嗯，好







在 2023-07-27 10:20:01，"pengliren" ***@***.***> 写道：

好的，整个测试环境文档也行

**Comment by xl-xueling** [comment]
整理了一篇ICE的部署和使用文档：https://dtstep.com/archives/4601.html


有问题随时沟通~













在 2023-07-27 10:20:01，"pengliren" ***@***.***> 写道：

好的，整个测试环境文档也行

**Comment by pengliren** [comment]
收到
