### ISSUE TITLE
centos7.9部署问题

### ISSUE THREAD

**Issue by renlw123** [xl-xueling/xl-lighthouse#17]
执行部署脚本卡在 ssh_keygen.exp 
![image](https://github.com/user-attachments/assets/65b9a01d-80de-4ae3-b3ba-6d02651edbfd)

**Comment by xl-xueling** [comment]
您好，可能跟你部署服务器的PS1命令提示符有关，我看你的命令提示符是： -bash-4.2$ ，在服务器上使用root账号，执行下面两个命令：
echo 'export PS1="[\u@\h \W]\\$ "' >> ~/.bashrc    
echo 'export PS1="[\u@\h \W]\\$ "' >> /home/work/.bashrc

修改一下当前操作系统的命令提示符，然后重新打开一个新的shell 再次执行部署脚本试一下。
另外，部署需要使用root账号，并且已经提前修改config目录下的nodelist节点配置。

**Comment by xl-xueling** [comment]
您好，还有问题吗，项目Readme最下面有我的微信，可以加下我的微信

**Comment by renlw123** [comment]
echo 'export PS1="[\u@\h \W]\$ "' >> ~/.bashrc
echo 'export PS1="[\u@\h \W]\$ "' >> /home/work/.bashrc
bash提示符修改了，部署也使用的root账户，nodelist节点配置也改了，使用的单机部署方式，但是还是老样子

**Comment by xl-xueling** [comment]
![image](https://github.com/user-attachments/assets/5eb79a0e-0a63-4d08-b756-1a5813c227f0)
这里提示符还是显示-bash-4.2$ 吗，还是已经显示修改后的格式了。
另外，你的服务器上是不是本来就有work账号，work账号还有其他地方环境变量有配置PS1，所以冲突了。可以修改下bin/config/standalone-deploy.json配置文件中的"deploy_user": "work",   修改成另外一个当前服务器不存在的账号名再试下。

可以加我微信 沟通方便些

**Comment by renlw123** [comment]
好的

**Comment by renlw123** [comment]
更换了用户后可以了
