### ISSUE TITLE
性能咨询

### ISSUE THREAD

**Issue by pengliren** [xl-xueling/xl-lighthouse#2]
有压测过的数据吗，比如我日数据写入10亿，峰值量级10w数据写入，大概需要机器配置，实时指标计算结果延迟大概多少？

**Comment by xl-xueling** [comment]
我目前做的压测还不是特别规范，所以暂时还不能给你提供比较有参考价值的数据。
xl-lighthouse的性能与三个因素有关：
1、原始消息上报的数量。
2、统计项的数量和运算类型。
3、统计结果的磁盘写入量。


如果只是从原始消息上报数量的角度还不能准确评估出所需的配置，不过峰值10w消息量的话，我初步感觉5台服务器(32核、128G）应该就差不多够用了，另外有条件的话最好选择SSD磁盘、千兆级或以上的网卡。

在 2023-07-28 18:53:27，"pengliren" ***@***.***> 写道：

有压测过的数据吗，比如我日数据写入10亿，峰值量级10w数据写入，大概需要机器配置，实时指标计算结果延迟大概多少？

**Comment by xl-xueling** [comment]
延迟大概是1~2分钟，上线后多关注下spark任务的监控页面，4040端口访问的那个页面。




在 2023-07-28 19:46:12，"xueling" ***@***.***> 写道：

我目前做的压测还不是特别规范，所以暂时还不能给你提供比较有参考价值的数据。
xl-lighthouse的性能与三个因素有关：
1、原始消息上报的数量。
2、统计项的数量和运算类型。
3、统计结果的磁盘写入量。


如果只是从原始消息上报数量的角度还不能准确评估出所需的配置，不过峰值10w消息量的话，我初步感觉5台服务器(32核、128G）应该就差不多够用了，另外有条件的话最好选择SSD磁盘、千兆级或以上的网卡。

在 2023-07-28 18:53:27，"pengliren" ***@***.***> 写道：

有压测过的数据吗，比如我日数据写入10亿，峰值量级10w数据写入，大概需要机器配置，实时指标计算结果延迟大概多少？

**Comment by pengliren** [comment]
能拉个微信群？这样咨询会方便些

**Comment by xl-xueling** [comment]
加我微信，canyangwell

**Comment by xl-xueling** [comment]
加我微信，canyangwell



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月31日 10:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xl-xueling/xl-lighthouse] 性能咨询 (Issue #2) |

能拉个微信群？这样咨询会方便些
