### ISSUE TITLE
是否有其他的横坐标

### ISSUE THREAD

**Issue by KN33SOCK** [xl-xueling/xl-lighthouse#20]
用了一会发现好像只有时间跨度作为横坐标，能否将别的字段作为横坐标统计展示呢？

**Comment by xl-xueling** [comment]
您好：
开源版本的图表目前只支持使用时间作为横坐标，付费版本可以支持使用统计指标的维度字段作为横坐标，至于要不要在开源版本中添加这个功能，还需要再考虑一下。xl-lighthouse经过严格测试，请您放心使用，有任何问题，欢迎您随时反馈~
