### ISSUE TITLE
单机版部署成功，引用lighthouse-client无法连上远程服务

### ISSUE THREAD

**Issue by loupenghui** [xl-xueling/xl-lighthouse#7]
![image](https://github.com/xl-xueling/xl-lighthouse/assets/8335977/58a91b00-eae8-4cbb-b3f9-832af9fbeab6)
安装成功，使用sdk上报连不上远程服务
![image](https://github.com/xl-xueling/xl-lighthouse/assets/8335977/a2c73c67-164c-45fa-b34f-7e5735e19de7)
是sdk引用不对吗?
![image](https://github.com/xl-xueling/xl-lighthouse/assets/8335977/3a4112b6-c0d5-482c-9a5d-8749849bd2e4)
在springboot启动后初始化
![image](https://github.com/xl-xueling/xl-lighthouse/assets/8335977/095bba7c-d8c3-401c-ae25-26cf34fb1a61)
ice服务应该是正常的吧
![image](https://github.com/xl-xueling/xl-lighthouse/assets/8335977/3b6f4104-5820-4c3d-b184-c98bed09cc87)

**Comment by loupenghui** [comment]
![image](https://github.com/xl-xueling/xl-lighthouse/assets/8335977/095bba7c-d8c3-401c-ae25-26cf34fb1a61)
ice服务应该是正常的吧

**Comment by xl-xueling** [comment]
应该是单机部署服务器资源过低，没有正常启动，看一下部署路径的~/data/ice/nodeout目录下有没有异常日志。另外需要引入ice的依赖包

**Comment by xl-xueling** [comment]
我近期会增加一个支持自定义扩展，使用自己的rpc服务的功能，不必绝对依赖ice这个组件。

**Comment by loupenghui** [comment]
> 应该是单机部署服务器资源过低，没有正常启动，看一下部署路径的~/data/ice/nodeout目录下有没有异常日志。另外需要引入ice的依赖包
报错内容文件：
[ice_stderr.log](https://github.com/xl-xueling/xl-lighthouse/files/13682702/ice_stderr.log)
