### ISSUE TITLE
如何引用sdk推送数据

### ISSUE THREAD

**Issue by loupenghui** [xl-xueling/xl-lighthouse#8]
![image](https://github.com/xl-xueling/xl-lighthouse/assets/8335977/6d2257b4-2797-456a-8e2f-6ae54163e03d)
Web正常，sdk是哪个，有示例吗，可以帮忙调通下不，当前pom中依赖引用如下：
![image](https://github.com/xl-xueling/xl-lighthouse/assets/8335977/1e183590-0158-4e39-88b2-07ec61e93560)
另外，问题没有解决，能先别关闭吗，谢谢

**Comment by xl-xueling** [comment]
不是我关闭的，是你自己关闭的哈~，我看你close了，还以为通了呢
![image](https://github.com/xl-xueling/xl-lighthouse/assets/80948665/4754fb1a-e076-421b-b8f0-64a56ac017e6)

**Comment by xl-xueling** [comment]
ice启动正常了吗，看下还有异常日志没有，需要首先正常启动ice。

（1）、可以使用部署用户（deploy.json中的deploy_user为系统用户名）登录linux系统后，执行restart.sh重启服务。
（2）、查看nodeoutput中是否还有异常日志，单机部署时，如果系统资源过低可能会重启异常。不知道你的服务器的内存和cpu是多少。
（3）、客户端调用时需要引入的jar包有以下jar包


 <dependency>
            <groupId>com.dtstep.lighthouse</groupId>
            <artifactId>lighthouse-common</artifactId>
            <version>1.1.4</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <artifactId>*</artifactId>
                    <groupId>*</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.dtstep.lighthouse</groupId>
            <artifactId>lighthouse-client</artifactId>
            <version>1.1.4</version>
        </dependency>      

        <dependency>
            <groupId>com.zeroc</groupId>
            <artifactId>ice</artifactId>
            <version>3.6.5</version>
        </dependency>
        <dependency>
            <groupId>com.zeroc</groupId>
            <artifactId>icegrid</artifactId>
            <version>3.6.5</version>
        </dependency>      
         <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.11.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
            <version>1.1.7.3</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.javatuples</groupId>
            <artifactId>javatuples</artifactId>
            <version>1.2</version>
        </dependency>

**Comment by xl-xueling** [comment]
![image](https://github.com/xl-xueling/xl-lighthouse/assets/80948665/3d3b2c04-233e-4316-a11a-eb63e0b27623)
