### ISSUE TITLE
我用腾讯云机器部署的用的内网地址但是用公网访问失败了

### ISSUE THREAD

**Issue by wangze-TIM** [xl-xueling/xl-lighthouse#9]
我这边看访问web页面发现访问后端接口是用的内网地址
![微信截图_20240407132152](https://github.com/xl-xueling/xl-lighthouse/assets/76514558/a2ff855c-cc4f-42d4-a8fa-50dbc32bc364)

**Comment by wangze-TIM** [comment]
找到了 需要找前端代码里面修改

**Comment by xl-xueling** [comment]
嗯，有问题随时反馈~

**Comment by xl-xueling** [comment]
我之前打的包有个问题，如果您是使用我releases里的发行版部署的，可能部署完成后，web端的图表会显示System Error，我已经修复了，如果遇到这个问题，可以重新下载发行版再部署一下。如有问题，随时反馈~

**Comment by wangze-TIM** [comment]
![image](https://github.com/xl-xueling/xl-lighthouse/assets/76514558/b5a33d1c-086c-4f00-9291-f817ed64e5f3)
我用新的版本部署redis出现问题

**Comment by wangze-TIM** [comment]
112007:M 12 Apr 2024 20:14:56.830 # Module /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so failed to load: /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so: cannot open shared object file: No such file or directory
112007:M 12 Apr 2024 20:14:56.831 # Can't load module from /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so: server aborting


redis编译有问题吧

**Comment by wangze-TIM** [comment]
112007:M 12 Apr 2024 20:14:56.830 # Module /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so failed to load: /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so: cannot open shared object file: No such file or directory
112007:M 12 Apr 2024 20:14:56.831 # Can't load module from /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so: server aborting


redis编译有问题吧

**Comment by xl-xueling** [comment]
用的什么操作系统



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月12日 20:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xl-xueling/xl-lighthouse] 我用腾讯云机器部署的用的内网地址但是用公网访问失败了 (Issue #9) |

image.png (view on web)
我用新的版本部署redis出现问题

**Comment by wangze-TIM** [comment]
centos 8.4

**Comment by xl-xueling** [comment]
嗯，是，你用的什么操作系统，版本号是多少



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月12日 20:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xl-xueling/xl-lighthouse] 我用腾讯云机器部署的用的内网地址但是用公网访问失败了 (Issue #9) |

112007:M 12 Apr 2024 20:14:56.830 # Module /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so failed to load: /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so: cannot open shared object file: No such file or directory
112007:M 12 Apr 2024 20:14:56.831 # Can't load module from /usr/soft/lighthouse-2.1.1/plugins/redis-roaring/build/libredis-roaring.so: server aborting

redis编译有问题吧

**Comment by wangze-TIM** [comment]
CentOS Linux release 8.4.2105

**Comment by wangze-TIM** [comment]
嗯嗯 好的

**Comment by xl-xueling** [comment]
是我前几天修改时有个编译参数配置错了，已修复，下载2.1.2版本部署~

**Comment by wangze-TIM** [comment]
收到

**Comment by wangze-TIM** [comment]
你好 如果是在原有的项目升级 命令是什么

**Comment by xl-xueling** [comment]
还没有这个功能，我会考虑加一个，得过几天才能提供！

**Comment by wangze-TIM** [comment]
您好 如果我这边需要升级机器配置 机器需要重启 又没有一键启动服务脚本

**Comment by xl-xueling** [comment]
有啊，有启动，restart_all.sh整个集群重启,包括依赖组件的重启，restart.sh只重启lighthouse



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月14日 13:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xl-xueling/xl-lighthouse] 我用腾讯云机器部署的用的内网地址但是用公网访问失败了 (Issue #9) |

您好 如果我这边需要升级机器配置 机器需要重启 又没有一键启动服务脚本

**Comment by wangze-TIM** [comment]
好的 谢谢了。

**Comment by xl-xueling** [comment]
只是现在还没有版本升级的功能，我下周给你提供这个功能



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月14日 13:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xl-xueling/xl-lighthouse] 我用腾讯云机器部署的用的内网地址但是用公网访问失败了 (Issue #9) |

您好 如果我这边需要升级机器配置 机器需要重启 又没有一键启动服务脚本

**Comment by xl-xueling** [comment]
重启，用系统部署账号执行，默认为work账号，密码在deploy.json中有默认配置的系统登录密码



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月14日 13:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xl-xueling/xl-lighthouse] 我用腾讯云机器部署的用的内网地址但是用公网访问失败了 (Issue #9) |

您好 如果我这边需要升级机器配置 机器需要重启 又没有一键启动服务脚本

**Comment by xl-xueling** [comment]
如果集群增加节点，是需要重新部署的，只增加内存和cpu不用部署



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月14日 13:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xl-xueling/xl-lighthouse] 我用腾讯云机器部署的用的内网地址但是用公网访问失败了 (Issue #9) |

好的 谢谢了。

**Comment by wangze-TIM** [comment]
<img width="1797" alt="171576ca1b883014fc3c714a5dfd77c" src="https://github.com/xl-xueling/xl-lighthouse/assets/76514558/1b8d1227-c326-4b4c-8e88-f84eb97fa286">
有显示问题

**Comment by xl-xueling** [comment]
@wangze-TIM ，好的，收到，是Limit数据的维度标签没有显示出来，我修改一下。

**Comment by xl-xueling** [comment]
@wangze-TIM ,Limit计算维度标签显示问题已修复，另外，一键升级功能已完成~

**Comment by xl-xueling** [comment]
> 我怎么在lighthouse-2.1.2的版本直接升级 有没有简单说明 谢谢

稍等，我写一个

**Comment by xl-xueling** [comment]
> 我怎么在lighthouse-2.1.2的版本直接升级 有没有简单说明 谢谢

一键升级参考文档：https://dtstep.com/zh/management/06.html
